### PR TITLE
Provide basic installation script for unix-like systems.

### PR DESCRIPTION
**Pull request by sten0**
Provide basic installation script for unix-like systems.

Signed-off-by: Nicholas D Steeves nsteeves@gmail.com

### CODE REVIEW

**Comment by tshprecher** [comment]
Out of curiosity, are you using this project for anything? I'm asking because if there are active users, I may consider fixing what I think is deficient and remove the big "work in progress" banner at the top of the README.

Are you using this to actually clean up code comments? The classifier needs some work. There are way too many false positives. I have some ideas on how to reduce them, but I haven't followed up.

**Comment by tshprecher** [comment]
Regarding this change, I don't believe there's a strong reason to add this. The user should be using the standard 'go get' command to retrieve and compile the binary. He/she should then point their $PATH to the bin/ directory in the $GOPATH.

**Comment by tshprecher** [comment]
oh, I see where you may be using this:

https://github.com/sten0/btrfs-progs/commit/ab7e106c419d8719b4eb6a44ffd8611eae9051de

**Comment by sten0** [comment]
On 13 May 2016 at 17:23, Tal Shprecher notifications@github.com wrote:

> oh, I see where you may be using this:
> 
> sten0/btrfs-progs@ab7e106
> https://github.com/sten0/btrfs-progs/commit/ab7e106c419d8719b4eb6a44ffd8611eae9051de
> 
> Honestly, I did that using sed with a provided mispellings list, then used
> emacs' ispell-comments-and-strings.  Only then did I look into time-saving
> alternatives--in the past I've frequently spent more time getting
> time-saving programs to work then it would have taken to actually do the
> work without them.  eg: scripting Palimpsest OCR to embed a plain-text
> layer into non-full-text-searchable articles from JSTOR.

On 13 May 2016 at 16:46, Tal Shprecher notifications@github.com wrote:

> Are you using this to actually clean up code comments? The classifier
> needs some work. There are way too many false positives. I have some
> ideas on how to reduce them, but I haven't followed up.

Yeah, I noticed that.  For now it looks like lucasdemarchi's codespell
(already packaged for Debian) + ispell-comments-and-strings is what I'll
use, but I will eagerly keep an eye on the gospell ;-)  My next typo review
will probably be in September when I'll do a survey of time-saving programs
before slogging through it.

**Comment by tshprecher** [comment]
I'll probably improve this before September. Thanks for your interest. Improvements in the actual classifier are welcome. There's some really low hanging fruit here.

**Pull request closed without merging**
